[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

# Explicit redirect rule for AASA file
[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/api/apple-app-site-association"
  status = 200
  force = true
  headers = {Content-Type = "application/json"}

[[redirects]]
  from = "/apple-app-site-association"
  to = "/api/apple-app-site-association"
  status = 200
  force = true
  headers = {Content-Type = "application/json"}